services:
  osrm:
    image: ghcr.io/project-osrm/osrm-backend
    container_name: osrm-backend
    command: osrm-routed --algorithm mld /data/bristol-latest.osrm --port 5005
    ports:
      - "5005:5005"
    volumes:
      - ./osrm-data:/data
    restart: unless-stopped
